DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS concepts;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS universities;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS isfriendwith;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS needsa;

